### ISSUE TITLE
Logical Query Plan UI Settings not properly selectable

### ISSUE THREAD

**Issue by schoenja** [polypheny/Polypheny-DB#117]
When trying to select an option for the Logical Query Plan, clicking on the checkbox only changes the checkbox, while clicking on the text next to it changes the setting but not the checkbox.

![image](https://user-images.githubusercontent.com/7579761/70700293-cc03e400-1cca-11ea-852f-2009550f5f1e.png)

**Comment by vogti** [comment]
I can't reproduce this. Which browser do you use?

**Comment by schoenja** [comment]
> I can't reproduce this. Which browser do you use?

71.0 (64-bit) on Linux

I'll pull a clean copy soon and try whether it still happens.

**Comment by schoenja** [comment]
Update: Could not reproduce the issue with a fresh build from both master branches. Closing.
