### ISSUE TITLE
Improved AdapterSetting API

### ISSUE THREAD

**Issue by schoenja** [polypheny/Polypheny-DB#118]
## Issue with current API
The current `AdapterSetting` has various shortcomings, including:
- It is not possible to "atomically" update several settings at once
- Parsing of the different types is left to the user

This should basically be reworked.

## Open questions:
- [ ] How to handle relative paths (what are they relative to?) (see also: #113 )

## Decided on:
- [x] New API will be in the `ch.unibas.dmi.dbis.polyphenydb.adapter.settings` package, in the `core` subproject.
- [x] Performance is not a priority.

---
OLD:

@vogti A few questions directly to you:
- Where would you locate the new API? I would prefer to move it out of the `Store` class into its own package.
- How performant does the code have to be? I assume that changing the settings of an adapter will not be a common operation, so performance isn't the primary concern?

**Comment by vogti** [comment]
> Where would you locate the new API? I would prefer to move it out of the Store class into its own package.
As long as it is an adapter / store settings library, I would keep it in the adapter package. Nevertheless, we can move it into its own sub-package.

> How performant does the code have to be? I assume that changing the settings of an adapter will not be a common operation, so performance isn't the primary concern?
Yes, performance should not be the primary concern.

**Comment by schoenja** [comment]
> > Where would you locate the new API? I would prefer to move it out of the Store class into its own package.
> 
> As long as it is an adapter / store settings library, I would keep it in the adapter package. Nevertheless, we can move it into its own sub-package.
> 
So something like `ch.unibas.dmi.dbis.polyphenydb.adapter.settings` in the `core` subproject?
> > How performant does the code have to be? I assume that changing the settings of an adapter will not be a common operation, so performance isn't the primary concern?
> 
> Yes, performance should not be the primary concern.

Awesome, means I can put more thought into making it "nice to use"

**Comment by vogti** [comment]
> So something like ch.unibas.dmi.dbis.polyphenydb.adapter.settings in the core subproject?

Yes, sounds good.

**Comment by schoenja** [comment]
Marking this as blocked until the hub is completed. Otherwise there will probably be too much back and forth for now.
