### ISSUE TITLE
Return to store overview after deploying a store

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#119]
After a successful deployment of a store, there should be a redirect to the overview of the running stores.

**Comment by nilshansen94** [comment]
Fixed in https://github.com/polypheny/Polypheny-UI/commit/af64fbd4e126f7f55b005078320708036ea5d219

**Comment by vogti** [comment]
Currently the redirect happens independent of the outcome of the deployment. Is it possible to do the redirect only if the deployment has been successful?

**Comment by nilshansen94** [comment]
Fixed in https://github.com/polypheny/Polypheny-UI/commit/4b268a5e6e8b6cdf02a223d12eb751fe84e5932d
