### ISSUE TITLE
Validate store name in deploy dialog

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#121]
Add validation for store name in the deploy dialog. Check for

-  Uniqueness of the name
- Same rules as for table names (no special chars, no spaces, not starting with a number)

**Comment by vogti** [comment]
The uniqueness of the unique name is not checked in the deploy dialog.

**Comment by nilshansen94** [comment]
Fixed in https://github.com/polypheny/Polypheny-UI/commit/4b268a5e6e8b6cdf02a223d12eb751fe84e5932d
