### ISSUE TITLE
Show the visibility level of a dataset

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#148]
![grafik](https://user-images.githubusercontent.com/1682115/71084601-f277c280-2195-11ea-9834-9ee85a2732ed.png)

It would also be nice to show the visibility (e.g. with a globe symbol).

**Comment by nilshansen94** [comment]
You need to pull the latest version of the Polypheny-Hub to show the username of the owners.

**Comment by vogti** [comment]
Ok, thank you. Now it correctly shows the username.

**Comment by vogti** [comment]
Fixed
