### ISSUE TITLE
Polypheny Hub is not working on iPads

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#149]
There is an issue with the Polypheny-UI on iPads. The table with the available datasets is not rendered correctly. By (clicking) touching on the table, rows appear and disappear (always from top to bottom). 

![IMG_BB16F67B144C-1 2](https://user-images.githubusercontent.com/1682115/110607636-ad212580-818b-11eb-98ad-13b526aab2ab.jpeg)

Steps to reproduce: 
- Start Polypheny-DB on a computer and open port 8080 of your firewall
- Open Polypheny-UI on the iPad
- Navigate to Hub

For actual development at the UI you should start it as described on the [website](https://polypheny.org/documentation/UI-Dev-Env/). Please notice that you need to set the host parameter to access the site from a different machine: `ng serve --host 0.0.0.0`

**Comment by melisacrnica** [comment]
Hi,
I'd like to contribute to Polypheny for GSOC 2022. May I please be assigned this issue?

**Comment by heitzli** [comment]
Hi @melisacrnica it would be great if you could take care of that issue. I assigned it to you.

**Comment by vogti** [comment]
Hi @melisacrnica Do you have any questions?

**Comment by Rahulxx01** [comment]
Hello Team.
Can this issue be assigned to me?
I want to start working on this asap and understand the codebase accordingly since this is my first issue

**Comment by vogti** [comment]
Polypheny Hub has been discontinued
