### ISSUE TITLE
NPE in AvaticaRuntimeException

### ISSUE THREAD

**Issue by schoenja** [polypheny/Polypheny-DB#151]
The [`Util.needToImplement`](https://github.com/polypheny/Polypheny-DB/blob/master/core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/util/Util.java#L712) method may throw a `RuntimeException` with a `null` message if the object that caused the exception is `null` itself.

This may happen in [`SqlValidatorImpl.getValidatedNodeType`](https://github.com/polypheny/Polypheny-DB/blob/master/core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/validate/SqlValidatorImpl.java#L1526).

This may be called in [`SqlProcessorImpl.validate`](https://github.com/polypheny/Polypheny-DB/blob/master/dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/SqlProcessorImpl.java#L160). If line 160 throws a `RuntimeException`, this exception get wrapped in an `AvaticaRuntimeException`, which requires the message of the exception to be non-null.

This in turn causes a `NullPointerException` in the exception, hiding the actual exception.

Reproducing the issue:
- I will add more detailed instructions, but it happened with commit 7155e1033da06732a4532ec477db33c91e2190ac

**Comment by vogti** [comment]
Indirectly fixed by adding a null check for the validation exception message in the SQL query validation on instantiation of AvaticaRuntimeException.
