### ISSUE TITLE
Only one save settings button

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#175]
Remove the (broken) save setting buttons in the header of the groups and introduce one (large) save settings button per page (similar to the run button in the plan builder).

![grafik](https://user-images.githubusercontent.com/1682115/73198263-0caca500-4133-11ea-8027-160928be0ec7.png)

**Comment by prinsusinghal** [comment]
Hi, I am Prateek Agarwal from IIT Roorkee. I want to contribute to Polypheny for GSOC'21 and this looks like a good issue to start with so I want to work on it. Please assign it to me.

**Comment by prinsusinghal** [comment]
Hi @vogti, I have set up the environment on my pc using polypheny-control but now I am stuck on how to proceed. Can you please guide what to do next?

**Comment by vogti** [comment]
Polypheny Control makes it easy to set up and update Polypheny-DB, but it is not suitable for doing development. Please follow [this](https://github.com/polypheny/Polypheny-DB/discussions/286) on how to set up Polypheny-DB in your favorite IDE and [this](https://polypheny.org/documentation/UI-Dev-Env/) guide on how to manually build Polypheny-UI.

**Comment by dlwyl1997** [comment]
Hi @vogti !
I'm Yulin WANG and I would like to participate in the GSoC 2021 programme. I'm really interested in Polypheny, and I hope to start with this issue if available.
Looking forward to making contributions and cooperating with you all in the future. Thanks!

**Comment by vogti** [comment]
Hi @dlwyl1997, welcome to Polypheny! I have assigned the issue to you. Please follow this on how to set up Polypheny-DB in your favorite IDE and this guide on how to manually build Polypheny-UI. Feel free to ask here or open a thread in the discussions forum if you have any questions or experience any issues with setup.

**Comment by vogti** [comment]
Hi @dlwyl1997, is everything working fine? If you have any issues or need help getting started, please do not hesitate to either ask here or open a thread in the [discussion forum](https://github.com/polypheny/Polypheny-DB/discussions).

**Comment by dlwyl1997** [comment]
> Hi @dlwyl1997, is everything working fine? If you have any issues or need help getting started, please do not hesitate to either ask here or open a thread in the [discussion forum](https://github.com/polypheny/Polypheny-DB/discussions).

Thank you and I'm still trying to get familiar with the sophisticated sructure of  the docs and codes in the repository, in order to find the relevant part to this issue. Could you give me a hint about where should I make the changes?
By the way, should I send you my CV to introduce myself recently?
Thanks!

**Comment by nilshansen94** [comment]
Hi @dlwyl1997. I admit, the Angular component for the configuration manager could be named in a better way. The component can be found in the following path: `Polypheny-DB-UI/src/app/views/forms/form-generator
`. There you can make the required changes.
We are happy if you can send us your CV by mail.

**Comment by dlwyl1997** [comment]
> Hi @dlwyl1997. I admit, the Angular component for the configuration manager could be named in a better way. The component can be found in the following path: `Polypheny-DB-UI/src/app/views/forms/form-generator `. There you can make the required changes.
> We are happy if you can send us your CV by mail.

That's helpful. Thanks!
