### ISSUE TITLE
Hub URL is not allowed to contain a trailing slash

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#178]
If the hub URL has a slash at the end, it is not working. Allow the URL to include a trailing slash to improve UX.

**Comment by nilshansen94** [comment]
Can you make an example of a URL that does not work?
For me, the following work:
https://hub.polypheny.org/index.php
https://hub.polypheny.org/
https://hub.polypheny.org
What is not supported is the following (and I don't consider this a valid URL):
https://hub.polypheny.org/index.php/
