### ISSUE TITLE
Wrong position of separation line in refinement options of graphical querying

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#179]
![grafik](https://user-images.githubusercontent.com/1682115/73350216-eac73580-428c-11ea-8665-42e59951a0a5.png)

**Comment by datomo** [comment]
Fixed by [c46eae4e06d2dec5a9048ebe599248aeea546f72](https://github.com/polypheny/Polypheny-UI/commit/c46eae4e06d2dec5a9048ebe599248aeea546f72) in [Polypheny-UI](https://github.com/polypheny/Polypheny-UI)
