### ISSUE TITLE
Improve query parsing SQL console in the UI

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#188]
It is currently not possible to execute queries containing a ";". For example:
```sql
select * from emps where name like '%;%'
```

**Comment by S-Harshit** [comment]
Hi, my name is Harshit I wanted to contribute to Polypheny for GSOC'21 and this looks like a good issue to start with so I want to work on it

**Comment by vogti** [comment]
Hi Harshit, welcome to Polypheny! I have assigned the issue to you.

**Comment by vogti** [comment]
@S-HarshitI have just realized that the description of this issue might not be detailed enough. It is only indicated by the issue title and the **A-ui** label that this issue only occurs when submitting SQL queries using the UI. Polypheny-DB itself is able to execute queries containing semicolons since internally, a query is always one statement and does never consist of multiple statements.

The problem described by this issue is with the separation of queries received from the SQL console in the UI. Currently, we simply do a `str.split(";")` (see org/polypheny/db/webui/Crud.java at line 711). To resolve this issue, it needs a more sophisticated approach for this splitting. 

To give you some test cases:
```
select * from emps where name like '%;%';
select * from emps where name like 'a'';';
``` 
As you see in the second example (and document on the [website](https://polypheny.org/documentation/PolySQL/Basics/)) single quotes are escaped by doubling it. This means, you might be able to implement a solution by simply counting the number of single quotes. If the number is even, a semicolon indicates the end of a line. If the number is odd, a semicolon is simply a character in a string. 

But this is only one approach. Maybe you have an idea for a more elegant solution I have overlooked. In this case, please go ahead.

**Comment by S-Harshit** [comment]
@vogti I am having a little trouble setting up the environment I read the documentation but I am still having issues so if their is a  dev mailing list or something where I can ask about issues related to setting up the environment ,I didn't wanted to ask here since it is not related to this particular issue.

**Comment by vogti** [comment]
@S-Harshit I took your question as an opportunity to activate the GitHub discussion function: https://github.com/vitrivr/cottontaildb/discussions We already planned to do that since quite some time. This allows us to keep everything at one place.

**Comment by vogti** [comment]
Please make sure this link: https://github.com/polypheny/Polypheny-DB/discussions I first copied the wrong link.

**Comment by S-Harshit** [comment]
> @S-Harshit I have just realized that the description of this issue might not be detailed enough. It is only indicated by the issue title and the **A-ui** label that this issue only occurs when submitting SQL queries using the UI. Polypheny-DB itself is able to execute queries containing semicolons since internally, a query is always one statement and does never consist of multiple statements.
> 
> The problem described by this issue is with the separation of queries received from the SQL console in the UI. Currently, we simply do a `str.split(";")` (see org/polypheny/db/webui/Crud.java at line 711). To resolve this issue, it needs a more sophisticated approach for this splitting.
> 
> To give you some test cases:
> 
> ```
> select * from emps where name like '%;%';
> select * from emps where name like 'a'';';
> ```
> 
> As you see in the second example (and document on the [website](https://polypheny.org/documentation/PolySQL/Basics/)) single quotes are escaped by doubling it. This means, you might be able to implement a solution by simply counting the number of single quotes. If the number is even, a semicolon indicates the end of a line. If the number is odd, a semicolon is simply a character in a string.
> 
> But this is only one approach. Maybe you have an idea for a more elegant solution I have overlooked. In this case, please go ahead.


![image](https://user-images.githubusercontent.com/65359506/110777778-821bfc00-8287-11eb-9808-5fc8ef559a95.png)
 
does it have to sperate queries even when they are entered in same line? (example as in image)
because I decided to do str.split(";\n") , it works except if the input has multiple query in the same line.

**Comment by vogti** [comment]
This is indeed not a bad idea to split by semicolon followed by a line break. But as you have pointed out, this does not work for multiple queries in one row. Furthermore, this will also cause other issues, e.g.:

- If the value contains a line break `select * from emps where name like ';\n';` Of course, more unlikely than a single semicolon but possible.
- If there is a space after the semicolon. `select * from emps where name like ';'; `

Especially the later one is quite likely to happen and would introduce new issues compared to the current situation. 

I think we should find a real solution for this issue. It might be possible to do something similar to the naive approach I've sketched above but with regex. I found something similar on stackoverflow: https://stackoverflow.com/a/18893443

**Comment by S-Harshit** [comment]
Tests are failing on my pull request, have I missed something?

**Comment by vogti** [comment]
There has been an issue with the tests on the GitHub Actions CI. We just migrated to GitHub Actions a few days ago, since Travis discontinued its open source plans. So there still some minor issues we are working on. The tests are now running again.
