### ISSUE TITLE
Correct rendering of HTML in data placement table

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#194]
Manuel placements should be displayed bold in the data placement overview in the schema manager. The HTML is currently not rendered.

**Steps to reproduce:**

- Add placement for a table
```sql
ALTER TABLE emps ADD PLACEMENT hsqldb
```

- View placements in schema manager
`http://HOST:8080/#/views/schema-editing/public.emps`

**Comment by nilshansen94** [comment]
This issue was fixed in https://github.com/polypheny/Polypheny-UI/commit/50dbbdda07878b5419ec038a5f11600bf26443c2
(see https://github.com/polypheny/Polypheny-DB/issues/112)
