### ISSUE TITLE
Rendering bug in UI query plan builder

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#255]
There is a rendering bug in the query plan builder. In Firefox, it happens nearly all the times. 

![grafik](https://user-images.githubusercontent.com/1682115/91021939-c51cc780-e5f4-11ea-9a17-e17f90478822.png)

**Comment by Pawanupadhyay10** [comment]
hi,@vogti I will like to get started on this issue, will u assign this issue to me . Thanks.

**Comment by Pawanupadhyay10** [comment]
I am new here ,May you pls guide me to start working on this issue via assigning this issue to me. Thanks.

**Comment by vogti** [comment]
Hi @Pawanupadhyay10, welcome to Polypheny! I have assigned the issue to you. Please follow [this](https://github.com/polypheny/Polypheny-DB/discussions/286) on how to set up Polypheny-DB in your favorite IDE and [this](https://polypheny.org/documentation/UI-Dev-Env/) guide on how to manually build Polypheny-UI. Feel free to ask here or open a thread in the discussions forum if you have any questions or experience any issues with setup.

**Comment by Pawanupadhyay10** [comment]
hey, after setup of ui i got this error, how can i remove it
![image](https://user-images.githubusercontent.com/52281814/113688852-50ac1a00-96e7-11eb-80af-9a3674d7fa77.png)
moreover , let me know in which file i need to add or edit the code so as to complete above task.

**Comment by nilshansen94** [comment]
Hi @Pawanupadhyay10, the component for the query plan builder can be found in `/Polypheny-DB-UI/src/app/views/querying/relational-algebra`. There is also a subfolder (`node`) with the component for the plan builder nodes.

**Comment by Pawanupadhyay10** [comment]
hi @nilshansen94,i found it in polypheny-ui , but when i went to query->plan builder , then there is no plan and even after using import button , i tried to create a plan and run it using run button on ui ,but no plan created.
![image](https://user-images.githubusercontent.com/52281814/113739943-e6fb3280-971d-11eb-92c6-a7b034ff57e0.png)
why it is so, what i need to do to make a plan on it.
so that i come to know about my task properly.

**Comment by vogti** [comment]
You can drag'n'drop operators from the left menu:

https://user-images.githubusercontent.com/1682115/113742152-9aeec480-9702-11eb-91a2-e278c83ec93c.mov

**Comment by Pawanupadhyay10** [comment]
![image](https://user-images.githubusercontent.com/52281814/113895380-8dab0600-97e6-11eb-91be-f8557d4fc5c0.png)

hey, see whenever after adding onChange() in the code and saving i made the plan builder and at every 1st time there is no rendering in the UI, in firefox, but after refreshing ,rendering comes in ui.
do you have any suggestions ,what else i can do to remove this bug perfectly from the firefox, there is no problem in crome .  
code
/*export class NodeComponent implements OnInit,OnChanges,AfterViewInit {
  constructor() { }
  @ViewChild('nodeEle', {static: false}) public nodeEle: ElementRef;
  @Input() node: Node;
  @Output() autocompleteChanged = new EventEmitter();
  public highlighted = "node1";
  ngOnInit() {
  }
  ngOnChanges(){
  }
  */

**Comment by nilshansen94** [comment]
Hi @Pawanupadhyay10, what I can see in the screenshot in the URL is that in the firefox you were on `localhost:8080`. This is the UI served by Polypheny-DB. If you want to see the life changes you made in the code you have to go from `localhost:8080` to `localhost:4200`. I suggest to add a bookmark to avoid this mistake.
What did you do so far to make it work in the Firefox browser? I suppose you were working with the Firefox developer tools?

**Comment by Pawanupadhyay10** [comment]
hi @nilshansen94 ,whatever changes i made is in polypheny-ui and after this i found that it will be push in polypenyl-ui repo,and i don't have access for it, so can you let me know which files i need to edit in polypheny-DB only  .Not like this "/Polypheny-DB-UI/src/app/views/querying/relational-algebra" because i found this file location in polypheny-ui not in polypheny-db.

**Comment by Pawanupadhyay10** [comment]
![image](https://user-images.githubusercontent.com/52281814/114131137-aa972480-991f-11eb-8344-d517cb5554e2.png)
while pushing code,can you guide pls.

**Comment by nilshansen94** [comment]
Hi @Pawanupadhyay10, you have to fork the Polypheny-UI project and commit to your own repository. When the changes are ready, you can create a pull request.

**Comment by Pawanupadhyay10** [comment]
ok,thanks.

**Comment by Pawanupadhyay10** [comment]
Have a look on my PR in polypheny-UI.
