### ISSUE TITLE
SQL aggregations return incorrect values

### ISSUE THREAD

**Issue by datomo** [polypheny/Polypheny-DB#277]
Aggregate functions seem to always return the same value MIN of the column (tested MIN, MAX and COUNT).

![SQL_aggregate](https://user-images.githubusercontent.com/5930207/107833741-87734d00-6d94-11eb-96d8-26bec1e2b2d0.png)

Tested when using the frontend, as well as `StatisticQueryProcessor`.

**Comment by vogti** [comment]
It seems to be a caching issue. After resetting the cache, it returns the correct result for the first aggregation query executed and then continues to return that result regardless of the query. I am looking into the problem.
