### ISSUE TITLE
Search function for the query history

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#282]
The SQL query history in the UI is extremely helpful. But if you are searching for a query you have executed a long time ago, you need to scroll through the whole list. It would therefore be extremely helpful to add a search function for the query history. 

![Bildschirmfoto 2021-03-10 um 15 45 01](https://user-images.githubusercontent.com/1682115/110647156-df487c80-81b7-11eb-94e5-4c3e0b0a8932.png)

It would be nice if the search field expends when clicking on it.

**Comment by earthshakira** [comment]
I'm planning to work on this issue is it alright ?

**Comment by vogti** [comment]
Hi Shubham, welcome to Polypheny! I have assigned the issue to you. Feel free to ask here or open a thread in the [discussions forum](https://github.com/polypheny/Polypheny-DB/discussions) if you have any questions or experience any issues with setup. This also helps us to improve our documentation.

**Comment by earthshakira** [comment]
Hi the instructions were pretty good and setup was very easy, I was able to complete most part of this issue, here's the [pull request](https://github.com/polypheny/Polypheny-UI/pull/40). Please guide me in the review process. Thanks and Regards

**Comment by earthshakira** [comment]
Hi! @vogti , the merge is complete at [pull request](https://github.com/polypheny/Polypheny-UI/pull/40). So can this issue be closed ?
