### ISSUE TITLE
Authentication for control 

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#291]
> This is a rather large issue for beginners.

With [Polypheny Control](https://github.com/polypheny/Polypheny-Control) we have an easy-to-use deployment and update tool for Polypheny-DB. But with the recent and planned additions to Polypheny-DB like querying the file system of the host machine, this tool also adds some severe security issues since the start-up arguments for enabling these features can be changed in Polypheny-Control.

It would therefore make sense to add an authentication to Polypheny Control. A system to support multiple user / password combinations would be nice, but a solution only supporting one password would be sufficient as well. It is important to also protect all methods of the REST API. The password should not be required when connecting from localhost.

**Comment by VishalDalwadi** [comment]
Hello. I am Vishal and I would like to participate in GSoC 2021 and contribute to this project. I would like to start by solving this issue.

**Comment by VishalDalwadi** [comment]
I know I haven't been assigned this problem. But I have thought of a solution. We add a file to store all the name-password combinations. To secure the passwords in this file we can use the [crypt](https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/digest/Crypt.html) method. The client `onConnect` must send the name and password, which we verify in the `addClient` method. If the credentials are invalid we do not add the client. Additionally, we add a command / tool for adding clients to the file so that users don't have to type out the files themselves.
Does this seem alright to you?
I do have some questions though.
1. Where should the password file be stored?
2. This does introduce a breaking change. So are you okay with this?
3. Should authentication "timeout" after sometime? It may happen when session timeout happens but does it have to be a different value?

**Comment by vogti** [comment]
Hi Ybrahin, welcome to Polypheny! Yes, this issue is available. I have now assigned it to you. Thank you for taking care of this.
Yes, this sounds good! Regarding your questions:
1.) Polypheny stores all files in a `.polypheny` folder in the users home directory. I suggest storing this file there too. 
2.) I suggest allowing connections from localhost without authentication as default (with a startup argument or config setting to enable this also for localhost).
3.) No, session timeout should be sufficient. But having a config option would be nice as well.

**Comment by VishalDalwadi** [comment]
@vogti I am able to create the password file, add/remove/modify user data with the commands and secure the start/stop/restart/update commands. Now, I will start with securing the REST API endpoints. I believe I would have to enable SSL to secure the data (password and other data). Can you please confirm this so I can go ahead with the implementation? 
Also should I make a separate PR for this and the REST API?

**Comment by vogti** [comment]
This sounds very good. Having SSL support would of course be nice. But we would need to generate self-signed certificates on startup and / or have an option to provide SSL certificates. With self-signed certificates we can not really gain much since man-in-the-middle attacks are still possible. I therefore suggest keeping it either completely plain-text or allow enabling SSL support with a config option and provided certificates. What do you think?

I have just added a class called `PolyphenyControlConnector` which allows interacting with the REST API. This should simplify testing for you. Furthermore, I have added a simple integration test.

**Comment by VishalDalwadi** [comment]
Okay. That sounds good. I would add a config option for ssl certificates.

**Comment by vogti** [comment]
Hi @VishalDalwadi, is everything working fine? If you have any issues or need help getting started, please do not hesitate to either ask here or open a thread in the [discussion forum](https://github.com/polypheny/Polypheny-DB/discussions).

**Comment by VishalDalwadi** [comment]
Hi @vogti. Yes, everything is working fine. I am still working on the issue. I think I will be done by monday. I'm sorry I haven't been able to do coding for a few days in the past week. But I will get the task done. Thanks.

**Comment by vogti** [comment]
Perfect :) There is no need to hurry. I just wanted to ask if you need any assistance. I am already looking forward to your pull request.

**Comment by VishalDalwadi** [comment]
Hey, @vogti . I am mostly done but having some problems with ssl. I haven't dealt with ssl before and don't feel confident about it. So I think someone more knowledgable than me should do it.
