### ISSUE TITLE
Improve design of Polypheny Control on small screens

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#295]
The UI of Polypheny Control is very basic and does not work well on smaller screens. 

![Bildschirmfoto 2021-03-14 um 14 25 14](https://user-images.githubusercontent.com/1682115/111070262-1f1da580-84d1-11eb-870a-27131ce37eb8.png)

**Comment by prinsusinghal** [comment]
Hi @vogti , I want to work on this issue to start contributing as a part of GSOC 2021. I saw that this page is disturbed when viewed on smaller screens. So for this I need to make some changes in the front-end part so that this is not disturbed on smaller screens.

**Comment by prinsusinghal** [comment]
But I am having a doubt. How to set up the development environment for polypheny-control UI?

**Comment by vogti** [comment]
Hi @prinsusinghal, welcome to Polypheny! It would be great if you can take care of this issue. I have just assigned it to you. There is not much to set up. The code of the small UI is not separated as with Polypheny-UI but also in the Polypheny Control repo. You can find the HTML, CSS and JS files in `/src/main/resources/static/`. Importing Polypheny Control in your favorite IDE is similar as described for Polypheny-DB [here](https://github.com/polypheny/Polypheny-DB/discussions/286). The main-method is located in `/org/polypheny/control/main/Main.java`

**Comment by prinsusinghal** [comment]
ok....so firstly I will work on this issue. By the time I am unassigning myself on #175, and later on after completing this issue if issue #175 remains unassigned then I will start working on it otherwise I will work on some other issue.

**Comment by prinsusinghal** [comment]
@vogti , I have followed the instructions given [here](https://github.com/polypheny/Polypheny-DB/discussions/286), but I am stuck on how to open polypheny-control using its main method. Please guide me what shall I do.

**Comment by prinsusinghal** [comment]
@vogti , I have created a pull request in the polypheny-control repository. You can review it.
