### ISSUE TITLE
Compress and Expand icon in search bar of left-sidebar are not working

### ISSUE THREAD

**Issue by prinsusinghal** [polypheny/Polypheny-DB#296]
Compress and Expand icon in search bar of left-sidebar are not working. And also, they are not required and should be removed as they cause confusion regarding their use.
![2021-03-16 (2)_LI](https://user-images.githubusercontent.com/60322217/111275393-1a392d00-865c-11eb-9c7c-4ec96c295e7c.jpg)

**Comment by prinsusinghal** [comment]
@vogti , please verify this issue as in mine its not working. Also if this is a valid issue then I want to work on it.

**Comment by vogti** [comment]
Yes, they are not required in the monitoring, config, uml, query console and plan builder view. Thanks for pointing this out. It would be great if you can take care of removing these buttons.

**Comment by prinsusinghal** [comment]
sure I will do that

**Comment by prinsusinghal** [comment]
@vogti , I have created the pull request. You can review the PR [here](https://github.com/polypheny/Polypheny-UI/pull/42)

**Comment by nilshansen94** [comment]
Hi @prinsusinghal, thank you for your work. Unfortunately, the changes were a bit too radical. In some views, the compress and expand buttons are needed. If you go to the schema view or to the graphical querying view, you will see that they are actually very useful there. The correct approach would be to check if the items in the left sidebar are nested. If they are not, the buttons can be hidden.
To work on this, you will have to work on the `left-sidebar.component.ts` file as well. The class variable "nodes" in this file holds the sidebar elements and is of the type `SidebarNode` (the type declaration is actually missing), which is defined in a model that can be found in the following path: `src/app/models/sidebar-node.model.ts`. To check if a SidebarNode element is nested, you need to check if the field `children` is set and non-empty.

**Comment by SantanaJonathan** [comment]
Good day. Excuse me, can you pass me the repository where the project is to be able to make the change. I would appreciate it. Thanks.

**Comment by nilshansen94** [comment]
Hi @SantanaJonathan , [here](https://github.com/polypheny/Polypheny-UI) is the link to the Polypheny-UI repository. Feel free to fork the repository and submit a pull request.

**Comment by vogti** [comment]
Hi @SantanaJonathan, is everything working fine? If you have any issues or need help getting started, please do not hesitate to either ask here or open a thread in the [discussion forum](https://github.com/polypheny/Polypheny-DB/discussions).

**Comment by SantanaJonathan** [comment]
Hi @vogti. I'm working in it. Basically this should fix, what i mention @nilshansen94 in #325.
Also at the time of executing this project I got these errors. 
***
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! Polypheny-UI@1.0.0 start: `ng serve --aot -o`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the Polypheny-UI@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
***
I don't know if it has to do with the version of Angular used in the project

**Comment by SantanaJonathan** [comment]
I could already solve it. I already opened the page. Now I need to know which server it is connected to. Because I got a message "Server not responding: HttpErrorResponse: Http failure response for http://localhost:8082/getPageList: 0 Unknown Error". Please. Sorry for the inconvenience Mr. @vogti.

**Comment by datomo** [comment]
Hey @SantanaJonathan 
This error mostly appears when you only have Polypheny-UI running via `ng serve` but not Polypheny-DB itself.
Did you only start Polypheny-DB or Polypheny-UI?
Just report back if this is not the case or you need futhur assitsance..

**Comment by SantanaJonathan** [comment]
Good day. My error. I forget to run the Polypheny-DB. I want to run but I don't see the package.json. 
How the Polypheny-DB runs? Help me, please. Thanks.

**Comment by datomo** [comment]
Polypheny-DB is built with Java and therefore does not have a package.json.
The easiest way to run it would be to clone the repo and open it in your IDE, I prefer Intellij. 
After opening it, you should automatically have 2 preconfigured task ( Polypheny-DB & Polypheny-DB (RESET)), which start the project. 

When Polypheny-DB started correctly you will be able to access it via localhost:8080. 
After that you can run Polypheny-UI, which then allows to access it also via localhost:4200 and can be used to observe your changes.

I hope this helps, if you have any trouble just report back

**Comment by Marc13000** [comment]
Hey I was wondering if this issue has been resolved?
Otherwise I would like to try a hand at solving it!

**Comment by Marc13000** [comment]
I was thinking of creating a isSetChildren method in sidebar to check if the variable is [] and then just use that to check nesting of each of the "nodes". Am I taking the right approach to this @vogti ? I am an applicant for GSoC 2022.

**Comment by vogti** [comment]
Hey @Marc13000, welcome to Polypheny! Yes, the issue is still open. It would be great, if you can take care of it. I have assigned the issue to you. Please follow [this](https://polypheny.org/documentation/DB-Dev-Env/) and [this](https://polypheny.org/documentation/UI-Dev-Env/) for setting up Polypheny-DB and Polypheny-UI in your favorite IDE. Feel free to ask here or open a thread in the [discussions forum](https://github.com/polypheny/Polypheny-DB/discussions) if you have any questions or experience any issues with setup. Please consider joining our [Discord](https://chat.polypheny.org) and following us on [Twitter](https://twitter.com/polypheny) to get updates on the project.

**Comment by Marc13000** [comment]
The importing of Polypheny-DB is taking way too long for some reason.. Using just the UI files and setup I managed to come up with this:
 hideExpandandCollapse() {
     return this.nodes.map(this.isSetChildren).includes(true);
  }

  isSetChildren(node: SidebarNode) {
    return node.children.length !== 0;
  }

and add *ngIf with the function to the html for expand and collapse. If it looks right ill go ahead and do a pull request

**Comment by datomo** [comment]
Hey @Marc13000 
To solve this you cannot rely on the structure of the sidebar tree. You mainly need to check if settings are displayed, aka which page your are on.
If you then are on a settings page you can just hide the search box. 
When you only check if the nodes have children you potentially hide it on pages where schemas without children are displayed. I hope this helps, if not feel free to comment again.

**Comment by Marc13000** [comment]
Not sure what you mean by if settings are displayed.

**Comment by Marc13000** [comment]
Also i managed to import the DB in IntelliJ but not sure how to run it

**Comment by datomo** [comment]
You should be able to use one of the pre-configured run configs, either "Polypheny-DB" or "Polypheny-DB(reset) ".These are in intellij selected with the dropdown menu on the right side in the top taskbar. .
