### ISSUE TITLE
LIKE operator for the file store

### ISSUE THREAD

**Issue by nilshansen94** [polypheny/Polypheny-DB#310]
The implementation of the LIKE operator in the file store is not that great. It simply creates a regex pattern of the search string. This is unsafe and not according to the SQL standard. It would be great to implement the correct behavior of the LIKE operator. The code can be found in the following path: `Polypheny-DB/file-adapter/src/main/java/org/polypheny/db/adapter/file/Condition.java`. The implementation is found in the `matches` function at the bottom (`case: LIKE`).
The documentation of the LIKE operator can be found [here](https://www.w3schools.com/sql/sql_like.asp).
One possible approach is described in this [stackoverflow answer](https://stackoverflow.com/questions/898405/how-to-implement-a-sql-like-like-operator-in-java#answer-898461), but there might be even better solutions.

**Comment by syedsafi30** [comment]
Hello, @nilshansen94 I'd like to work on this issue as part of my contribution for GSOC so please assign this to me.

**Comment by vogti** [comment]
Hi @syedsafi30, welcome to Polypheny! I have assigned the issue to you. Please follow [this](https://github.com/polypheny/Polypheny-DB/discussions/286) on how to set up Polypheny-DB in your favorite IDE. Feel free to ask here or open a thread in the discussions forum if you have any questions or experience any issues with setup.

**Comment by JAgrit20** [comment]
@syedsafi30, actually I have already started working on this issue, and almost close to the fix,
I would request you to please work on some other issue, 
Thanks in advance

**Comment by syedsafi30** [comment]
Hi @JAgrit20, the issue was assigned to me a couple of days ago in which time I have made considerable progress towards it. I'm not sure why you didn't request it to be assigned to you earlier but may be you can look into the other issues which are still open?
 
Requesting @vogti to clarify what's to be done here.

**Comment by JAgrit20** [comment]
I believe you should send your PR first by the end of today and then I will after you, the best one that can be merged with the first preference would be given to you?

**Comment by vogti** [comment]
Hi @syedsafi30 and @JAgrit20. @syedsafi30 you are right. This issue is and continuous being assigned to you. I am happy to hear that it is working fine for you. If you have any problems, please do not hesitate to ask.

**Comment by erdengk** [comment]
If there is no one to solve this problem now, I want to try to solve it. @vogti
