### ISSUE TITLE
Cottontail-DB Adapter: LIMIT does not get propagated

### ISSUE THREAD

**Issue by ppanopticon** [polypheny/Polypheny-DB#357]
If I enter a query such as  `select * from cineast.features_averagecolor LIMIT 1` in the Polypheny DB query UI, then the LIMIT part does not get propagated to the Cottontail DB adapter. The respective parameter in _CottontailQueryEnumerable.buildSingleQuery_ is null.

**Comment by vogti** [comment]
I fixed this in the linked commit.
