### ISSUE TITLE
PostgreSQL-Adapter (remote): Problems when there is no connection to DB

### ISSUE THREAD

**Issue by ppanopticon** [polypheny/Polypheny-DB#361]
If I create a PostgreSQL-Adapter (remote), I encounter the following issues in case there is no connection to the database instance (e.g., because the port setting was wrong):

1. Polypheny-DB lets me create the adapter even though it cannot connect to the database. This is, for example, not possible with the Cottontain-DB adapter.
2. If I now start to define a schema using my broken adapter, creating a table on PostgreSQL obviously fails. However, Polypheny-DB still creates the table entry in its catalogue.
3. Because Polypheny-DB now "thinks" that there is data on PostgreSQL, the aforementioned, erroneous adapter cannot be dropped anymore. But it also seems to be impossible to drop the individual tables.

**Comment by vogti** [comment]
Fixed by https://github.com/polypheny/Polypheny-DB/commit/6c91b6da2be726850e77719283e472ce72185c6e
