### ISSUE TITLE
HttpInterface statistics are not updated

### ISSUE THREAD

**Issue by silvanheller** [polypheny/Polypheny-DB#382]
When executing requests against the http interface, no statistics are measured. The underlying cause seems to me that in https://github.com/polypheny/Polypheny-DB/blob/master/http-interface/src/main/java/org/polypheny/db/http/HttpInterface.java, the counters are only accessed, but never incremented.

To reproduce, simply execute any query against the http interface, e.g. with 
```
curl -X POST localhost:13137/sql -d '{"query": "SELECT * FROM emp"}'
```
and watch the statistics not being updated.

**Comment by vogti** [comment]
Thx, @silvanheller, for this bug report. This has been an artifact from the refactoring of the query interfaces. I have replaced it with counters for the supported query languages (MQL, SQL, CQL and Pig).

**Comment by vogti** [comment]
Added with #384
