### ISSUE TITLE
HttpInterface has no error logging

### ISSUE THREAD

**Issue by silvanheller** [polypheny/Polypheny-DB#383]
The HttpInterface has no logging for errors, which makes it hard to debug without setting up the whole stack locally. An easy way to include this would be to use the generic exception-handling method provided by Javalin (https://javalin.io/documentation#exception-mapping).

To reproduce, simply start polypheny via Control and perform any ill-formed query, e.g.

```
curl -X POST localhost:13137/sql -d "test"
```
and watch nothing being logged (i.e. written to the logfile), versus e.g. executing an erroneous query in the console.

**Comment by vogti** [comment]
Thx, @silvanheller, for this bug report and the suggested solution. I've added some basic error handling which returns an error result and appends the error message to the log.

**Comment by vogti** [comment]
Added with #384
