### ISSUE TITLE
Improve Insights on Number of active Monitoring Threads

### ISSUE THREAD

**Issue by hennlo** [polypheny/Polypheny-DB#395]
### Affected Areas

DB

### Feature Description

Improve Insights on Number of active Monitoring Threads.

The monitoring service currently supports dynamic thread pooling, starting with a number of `CoreSize` Threads that are active and working on monitoring events in the queue. This pool will spwan new threads up to the defined limit of `MaxPoolSize`.

However, currently we have no insights when the pool size changes and threads become active or leave the pool again.
Therefore an improvement is needed which logs these changes.

### Use Case(s)

During testing or benchmarking it is desirable to see how the monitoring backend behaves in certain situations.

### Possible solutions

Adapt the `MonitoringQueueImpl` to write to the application log whenever a new Thread joins the pool or leaves the pool(due to timeout).
This should be no permanent logging activity and only be called/logged when there indeed is a change in size.

**Comment by Slayzur02** [comment]
Hello! I want to contribute to Polypheny during GSoC 2022, and wanted to start with this issue. Could you assign it to me?Thank you.

**Comment by hennlo** [comment]
Hi @Slayzur02  it would be great if you could handle that issue. I assigned it to you.

**Comment by Slayzur02** [comment]
Hi @OmarMetmwah, I'm currently working on it, but you can also work on it if you want too.

**Comment by heitzli** [comment]
Hi @OmarMetmwah thank you for your interest in Polypheny. Since @Slayzur02 is already handling that Issue I would recommend you to pick another Issue from our list of good first issues (https://github.com/polypheny/Polypheny-DB/issues?q=is%3Aissue+is%3Aopen+label%3AE-good-first-issue).

**Comment by vogti** [comment]
Hi @Slayzur02 Do you have any questions?

**Comment by Slayzur02** [comment]
Hi @vogti Thank you so much for asking. I just created a pull request where I used a scheduled timer which checks every 500ms to see if the number of threads have changed. I'm not sure if it's optimal, and have noted some points of concern with the pull request.
