### ISSUE TITLE
Option to select a time interval for the dashboard

### ISSUE THREAD

**Issue by isabelge** [polypheny/Polypheny-DB#401]
### Affected Areas

DB, UI

### Feature Description

![dropdown](https://user-images.githubusercontent.com/43370060/155479564-8b25722d-596b-47aa-a359-2d351a653a9a.PNG)

Addition of a possibility to select the time interval for the dashboard. 

### Use Case(s)

Right now the dashboard has no possibility to select a specific time interval. It would be helpful to be able to choos a time interval in order to check a specific time interval.

### Possible solutions

Addition of dropdown menu in the `DashboardComponent` with time interval options (for example: all, 1 hour, 30 minutes, 15 minutes, 5 minutes...).  
Additionally within Polypheny-DB the `StatisticCrud`  (`getDashboardDiagram`) needs to be adjusted. The start time should be adjusted using the information from Polypheny-UI.

**Comment by zxie86** [comment]
Hi!
I would like to apply to Polypheny in the GSoC 22. I want to work on this issue to learn more about Polypheny.
Could you please assign me this issue? 

Thanks,
Kelly

**Comment by heitzli** [comment]
Hi @zxie86 it would be great if you could take care of this issue. I have just assigned it to you. To set up your Development Environment please refer to the following guides: [DB Development Environment](https://polypheny.org/documentation/DB-Dev-Env/) and [UI Development Environment](https://polypheny.org/documentation/UI-Dev-Env/).

**Comment by zxie86** [comment]
Hi,
I am trying to pass an array of TreeMap(one treemap for each time interval) from StatisticCrud (getDashboardDiagram) to the UI getDiagram(), but the UI gives an error "Property 'left' does not exist on type 'unknown'"(**value**.left  is unknown) when I tried to grab the response <DashboardData>res [0,1,...]. 

I wonder if I need to modify<DashboardData>, or approach this problem in a different way.

Thanks,
Kelly

**Comment by isabelge** [comment]
Hi @zxie86 
I am not sure if I understand your idea correct. I would suggest to only pass one time interval (only one TreeMap) to the UI. The idea is that only one time interval is displayed at the time. Therefore, I would not fetch the time intervall before it is selected.
If you have any further questions or if I misunderstood your idea, please feel free to ask again.

**Comment by zxie86** [comment]
Hi @isabelge 
My original idea was the time intervals will use the same dataset(the same end time).
Your suggestion would be every time the user choose a time interval, the UI will call the crud service. So the end time(current time) will be different time. Is it correct? If yes, that make more sense!

Thanks!

**Comment by isabelge** [comment]
Hi @zxie86 
Yes, exactly. And yes, the end time will be different every time, which means that with changing the interval the information is also updated.

**Comment by zxie86** [comment]
Hi @isabelge,
I created two pull requests. Please review and I am looking forward to receiving feedback. Thanks!

UI: https://github.com/polypheny/Polypheny-UI/pull/71
DB: https://github.com/polypheny/Polypheny-DB/pull/409

**Comment by GauravKumawat33** [comment]
Is the issue still open?

**Comment by vogti** [comment]
Hi @GauravKumawat33, welcome to Polypheny! No @zxie86 has already solved this issue and opened a pull request. But you can work on another good-first-issue.

**Comment by vogti** [comment]
Fixed in #409
