### ISSUE TITLE
Add ` -version` as additional command line option

### ISSUE THREAD

**Issue by hennlo** [polypheny/Polypheny-DB#424]
### Affected Areas

DB

### Feature Description

Add ` -v | --version` as additional command line option to retrieve the installed version of Polypheny.

Currently the `polypheny` command line hook does only support runtime flags such as:
```bash
NAME
        polypheny-db - Polypheny-DB command line hook.

SYNOPSIS
        polypheny-db [ -daemon ] [ -defaultSource <defaultSourceName> ]
                [ -defaultStore <defaultStoreName> ] [ -gui ] [ {-h | --help} ]
                [ -memoryCatalog ] [ -resetCatalog ] [ -resetDocker ]
                [ -testMode ]

OPTIONS
        -daemon
            Disable splash screen

        -defaultSource <defaultSourceName>
            Type of default source

        -defaultStore <defaultStoreName>
            Type of default store

        -gui
            Show splash screen on startup and add taskbar gui

        -h, --help
            Display help information

        -memoryCatalog
            Store catalog only in-memory

        -resetCatalog
            Reset the catalog

        -resetDocker
            Removes all Docker instances, which are from previous Polypheny
            runs.

        -testMode
            Special catalog configuration for running tests
```

### Use Case(s)

Easy to use functionality to obtain installed version of Polypheny

### Possible Solutions

Add option in PolyphenyDb.java alongside the existing options.

**Comment by Ejaz29** [comment]
Hi @hennlo,
I would like to work on this issue. After looking around the code, I found the file to add the option
https://github.com/polypheny/Polypheny-DB/blob/master/dbms/src/main/java/org/polypheny/db/PolyphenyDb.java
But for default value of version do I need to keep it as v0.8.1 ?

**Comment by hennlo** [comment]
Hi @Ejaz29 thanks for interacting with Polypheny.

There is no need to set or work with a default value here.
You can simply  print out the current configured version that is set in the code.

If you want to be extra fancy you can also print out the associated  commit id along the version.

I'll assign you the issue.

**Comment by Ejaz29** [comment]
I cannot find where the version is set in the code sir. Is this ok?
@Option(name = { "-version" }, description = "Displays installed version")
public boolean version = false;
 And In runPolyphenyDB  method
if ( version ) {
     log.info("Version 0.8.1");
}
I am new to open source sir, having a hard time looking at the vast code.

**Comment by Ejaz29** [comment]
I cannot find where the version is set in the code sir. Is this ok?
@option(name = { "-version" }, description = "Displays installed version")
public boolean version = false;
And In runPolyphenyDB method
if ( version ) {
log.info("Version 0.8.1");
}
I am new to open source sir, having a hard time looking at the vast code. And I unassigned me by mistake you can assign me @hennlo .

**Comment by hennlo** [comment]
@Ejaz29 Regarding the code snippet. Looks okay in general if you now include the correct version retrieved from `gradle.properties` file. 
For the option selection process, I would stick to the open source commonalities and use both `-v` and  `--version` to detect this option.
Please also think about  the fact that if the version parameter was requested the system shall not start.
Similiar to the `--help` function

**Comment by Ejaz29** [comment]
hey @hennlo,
Thanks for the help. Created a pull request please review it.

**Comment by rit-clone** [comment]
@hennlo I'd like to work on this issue, can you please assign it to me?
