### ISSUE TITLE
Error with Launching Polypheny-DB: Error message about "Something went wrong while restoring query interfaces from the catalog."

### ISSUE THREAD

**Issue by eda-ricercatore** [polypheny/Polypheny-DB#465]
### Operating System (Polypheny-DB)

macOS

### Polypheny-DB Version

v0.9.1

### Affected Areas

DB

### Client Operating System

macOS Sonoma 14.3

### Bug Description

Error with Launching Polypheny-DB: Error message about "Something went wrong while restoring query interfaces from the catalog."

While trying to launch, or start running, Polypheny-DB, I encountered the following error message in a splash screen.

"Error: Something went wrong while restoring query interfaces from the catalog."

When I clicked on the exit button, which is the only option that I have to interact with the splash screen, it terminates the execution/running of the Polypheny-DB application.

A screenshot of the error message is provided as follows.

![Screenshot of "Error: Something went wrong while restoring query interfaces from the catalog."](https://github.com/polypheny/Polypheny-DB/assets/18295279/2ba6de0f-6059-46b8-ab38-658503415336)

I am running Polypheny-DB on macOS Sonoma 14.3.

If possible, can you please kindly help me resolve this bug? Thank you so much, and have a great day!!!

### Reproduction Steps

Each time when I try to launch Polypheny-DB, the aforementioned error message occurs, and Polypheny-DB would crash subsequently.

### Expected Behavior

Polypheny-DB should launch normally.

### Relevant Log Output

```shell
Unfortunately, no log files are available.
```

**Comment by hennlo** [comment]
Hi @eda-ricercatore thanks for opening up this issue.

Was this the first time starting Polypheny on your machine? 
Could you try deleting the content of `~/.polypheny/` and see if this temporarily resolves the error?

**Comment by eda-ricercatore** [comment]
Dear Mr. @hennlo,
  Unfortunately, I am unable to do this, since all I have is the binary executable.

  The file/directory is: _Polypheny.app_.

  I downloaded the binary installer/file, _Polypheny-0.9.1.dmg_, from the following Web page.

  The contents of the binary installer/file, _Polypheny-0.9.1.dmg_, do not have a ``binary installer/file Polypheny-0.9.1.dmg``.
  
![Polypheny-app-no-hidden-directory](https://github.com/polypheny/Polypheny-DB/assets/18295279/0b9ab086-7d9e-4bb5-ba32-d57f5b102e13)

  I have included a screenshot of the contents of _Polypheny-0.9.1.dmg_ above.

**Comment by hennlo** [comment]
@eda-ricercatore Sorry mabye my response was a little ambiguous:
Look in your users home directory there should be a newly created folder after trying to start polypheny that is called: `.polypheny/`
You can try remove the content of this specific folder.

**Comment by eda-ricercatore** [comment]
Thank you so much for your help, Mr. @hennlo .

I have managed to get running, and it automatically launches the Polypheny-DB on a tab in my Web browser.

I appreciate your help.

Once again, thank you so much. Have a great day/weekend!!!

**Comment by hennlo** [comment]
Glad to hear it worked for you, we're still trying to mitigate this behaviour in the future. 👍
