### ISSUE TITLE
port 4200 is already in use 

### ISSUE THREAD

**Issue by alyaa999** [polypheny/Polypheny-DB#473]
### Bug Description

After terminating the UI code, the port remains in use, resulting in a failed build.

### Reproduction Steps

1-Execute ./gradlew npm_start to initiate the Polyphen UI code.
2-Terminate the running code by pressing Ctrl+C.
3-Re-execute ./gradlew npm_start.
4-Encounter a failed build.

### Expected Behavior

The expected behavior is that the Polyphen UI code restarts successfully after terminating the running code with Ctrl+C

### Relevant Log Output

```shell
unhandled exception occurred: Port 4200 is already in use. Use '--port' to specify a different port.
```

### Polypheny-DB Version

v0.9.1

### Affected Areas

UI

### Browser

Chrome, Edge

### Client Operating System

windows 10

**Comment by sroopsai** [comment]
<img width="1070" alt="image" src="https://github.com/polypheny/Polypheny-DB/assets/38998304/e31a71eb-0691-4dd3-82a3-72760af13665">

I reproduced the steps described above. I am not getting errors. The issue maybe port on your system is not closed properly.

**Comment by datomo** [comment]
Dear @alyaa999 
Thank you for this issue.
You get this error, when your system is already using the default development port used by Angular.

As visible in your error message you can simple adjust the port to an alternative for development.
(This port is different to the default port used by Polypheny in production, which can be adjusted via runtime config.)

As this is no issue with Polypheny-DB or Polypheny-UI, I will close this issue.
