### ISSUE TITLE
Duplicate registered cypher operator

### ISSUE THREAD

**Issue by Ahmed-Elgamel** [polypheny/Polypheny-DB#480]
The cypher registerer register the following operator twice:

        register( OperatorName.CYPHER_HAS_LABEL, new LangFunctionOperator( OperatorName.CYPHER_HAS_LABEL.name(), Kind.CYPHER_FUNCTION ) );

Is this intended?

**Comment by datomo** [comment]
Hey @Ahmed-Elgamel  
No, this is not intended, but as this does not have any influence on the system, we will change that with one of the future PRs.
