### ISSUE TITLE
Add information element for durations

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#51]
Add a special information element for durations. This element should already include the required stopwatch code. Furthermore, it should also be possible to simply provide a duration as long.

The element has to support interims and "sub durations". For every interim and sub duration there should be a label assigned. It would be nice if sub durations can also have interims (but this is not required).

`
d = new DurationElement("Execution Time");
d.start();

s1 = d.subDuration("Task 1");
s1.start();
TIME_CONSUMING_TASK_1
s1.end();

TIME_CONSUMING_TASK_2
d.interim("Foo");
TIME_CONSUMING_TASK_3

d.end();
`

The unit in which the duration it is displayed in the UI should be selected automatically. Furthermore, it should be possible to set the unit manually.

It would be nice if the durations can be visualized in the UI.

**Comment by nilshansen94** [comment]
Some examples to show the basic usage:
```java
InformationDuration duration1 = new InformationDuration( durationGroup );
duration1.start( "Task1" );
duration1.stop( "Task1" );
duration1.start( "Task2" ).setLimit(50);//the item will be highlighted if it took more than 50ms
    duration1.get("Task2").start("subTask");//subTask
    duration1.get("Task2").stop("subTask");
duration1.stop( "Task2" );
duration1.addNanoDuration( "NanoTask", 30_000_000 );
duration1.addMilliDuration( "MilliTask", 30 );
duration1.noProgressBar();//don't render a progress bar for this duration's elements
```
See InformationServerTest.java for more examples.
