### ISSUE TITLE
Add input elements for date/time types

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#63]
Add a calendar and time element in the UI to easily add and change fields with a date/time type.

**Comment by nilshansen94** [comment]
@vogti what do you think about [flatpicker](https://www.npmjs.com/package/flatpickr) ([demo](https://flatpickr.js.org/examples/))? Can you test it on an iPad?

**Comment by vogti** [comment]
Looks good and works perfectly on iPhone. On iPad it does not react well and is also slightly broken:
![grafik](https://user-images.githubusercontent.com/1682115/74782837-923ff280-52a4-11ea-8ff8-c994b277f874.png)

**Comment by vogti** [comment]
Is it possible to select the current value when editing?
