### ISSUE TITLE
Drop table and truncate table are not working

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#86]
![screen](https://user-images.githubusercontent.com/1682115/67146548-6ed05100-f28c-11e9-85f9-61410b298e6e.png)

**Comment by nilshansen94** [comment]
You have to type "test" to drop the table test (as it is describe above the table). But I see that the placeholder of the input-field is misleading.
I could change it in a way, that both "test" and "drop test" would work.

**Comment by vogti** [comment]
Ah, ok. Yes, I think allowing "test" as well as "drop test" is a good and pragmatic solution.

**Comment by vogti** [comment]
Writing `drop tablename` or `truncate tablename` activates the button but nothing happens when clicking it.
